spring:
  flyway:
    locations: classpath:db/migration/{vendor}

pmitz:
  remoteserver:
    repository:
      rdb:
        schema-name: dbo
        user-usage-table-name: usage
        user-limit-table-name: user_limit
        subscription-table-name: subscription
        subscription-plan-table-name: subscription_plan