[versions]

# Libraries
assertj-core-version = '3.27.6'
commons-dbcp2-version = '2.13.0'
h2database-h2-version = '2.4.240'
httpcomponents-client5-httpclient5-version = '5.5.1'
jackson-databind-version = '3.0.3'
json-path-version = '2.10.0'
junitJuniper-version = '6.0.1'
junitPlatformLauncher-version = '6.0.1'
logback-version = '1.5.20'
mockito-junitJuniper-version = '5.20.0'
mysqlConnectorJava-version = '8.0.33'
postgresql-version = '42.7.8'
slf4j-version = '2.0.17'
springboot-version = '4.0.1'
sqlserver-mssqlJdbc-version = '13.2.1.jre11'
testcontainers-version = '2.0.3'
wiremock-version = '3.13.1'
system-stubs-version='2.1.8'

# Plugins
benManesVersions-version='0.53.0'
owaspDependencyCheck-version='12.1.8'
springDependencyManagement-version = "1.1.7"
springJavaformatCheckstyle-version = '0.0.47'


[libraries]

# Common libraries
commons-dbcp2 = { group = 'org.apache.commons', name = 'commons-dbcp2', version.ref = 'commons-dbcp2-version' }
httpcomponents-client5-httpclient5 = { group = 'org.apache.httpcomponents.client5', name = 'httpclient5', version.ref ='httpcomponents-client5-httpclient5-version' }
jackson-databind = { group = 'tools.jackson.core', name = 'jackson-databind', version.ref = 'jackson-databind-version' }
json-path = { group = 'com.jayway.jsonpath', name = 'json-path', version.ref = 'json-path-version' }
slf4jApi = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j-version' }

# Database drivers
h2database-h2 = { module = 'com.h2database:h2', version.ref = 'h2database-h2-version' }
mysqlConnectorJava = { group = 'mysql', name = 'mysql-connector-java', version.ref = 'mysqlConnectorJava-version' }
postgresql = { group = 'org.postgresql', name = 'postgresql', version.ref = 'postgresql-version' }
sqlserver-mssqlJdbc = { group = 'com.microsoft.sqlserver', name = 'mssql-jdbc', version.ref = 'sqlserver-mssqlJdbc-version' }

# Testcontainers libraries
testcontainers = { group = 'org.testcontainers', name = 'testcontainers', version.ref = 'testcontainers-version' }
testcontainers-junitJuniper = { group = 'org.testcontainers', name =  'testcontainers-junit-jupiter', version.ref = 'testcontainers-version' }
testcontainers-mssqlserver = { group = 'org.testcontainers', name =  'testcontainers-mssqlserver', version.ref = 'testcontainers-version' }
testcontainers-mysql = { group = 'org.testcontainers', name =  'testcontainers-mysql', version.ref = 'testcontainers-version' }
testcontainers-postgresql = { group = 'org.testcontainers', name =  'testcontainers-postgresql', version.ref = 'testcontainers-version' }

# Library for CheckStyle
springJavaformatCheckstyle = { group = 'io.spring.javaformat', name = 'spring-javaformat-checkstyle', version.ref = 'springJavaformatCheckstyle-version' }

# Libraries for testing
assertj-core = { group = 'org.assertj', name = 'assertj-core', version.ref = 'assertj-core-version' }
junitJuniper = { group = 'org.junit.jupiter', name = 'junit-jupiter', version.ref = 'junitJuniper-version' }
junitPlatformLauncher = {group = 'org.junit.platform', name = 'junit-platform-launcher', version.ref = 'junitPlatformLauncher-version' }
logbackClassic = { group = 'ch.qos.logback', name = 'logback-classic', version.ref = 'logback-version' }
mockito-junitJuniper = { group = 'org.mockito', name = 'mockito-junit-jupiter', version.ref = 'mockito-junitJuniper-version' }
wiremock = { group = 'org.wiremock', name = 'wiremock', version.ref = 'wiremock-version' }
system-stubs= { group = 'uk.org.webcompere', name = 'system-stubs-jupiter', version.ref = 'system-stubs-version' }

[plugins]

springboot = { id = 'org.springframework.boot', version.ref = 'springboot-version' }
springDependencyManagement = { id = 'io.spring.dependency-management', version.ref = 'springDependencyManagement-version' }
owaspDependencyCheck = { id = 'org.owasp.dependencycheck', version.ref = 'owaspDependencyCheck-version' }
benManesVersions = { id = 'com.github.ben-manes.versions', version.ref = 'benManesVersions-version' }

